CREATE SCHEMA IF NOT EXISTS PUBLIC AUTHORIZATION postgres;

﻿CREATE TABLE IF NOT EXISTS PUBLIC.TB_HOSPEDE (
	ID_HOSPEDE serial PRIMARY KEY,
	NOME_HOSPEDE VARCHAR(120) NOT NULL,
	DOC_HOSPEDE VARCHAR(16) NOT NULL,
	TEL_HOSPEDE VARCHAR(12) NOT NULL	
);

CREATE TABLE IF NOT EXISTS PUBLIC.TB_CHECKIN (
	ID_CHECKIN SERIAL NOT NULL PRIMARY KEY,
	ID_HOSPEDE INTEGER NOT NULL REFERENCES TB_HOSPEDE(ID_HOSPEDE),
	DT_ENTRADA_CHECKIN TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DT_SAIDA_CHECKIN TIMESTAMP DEFAULT NULL,
	ADD_VEICULO_CHECKIN BOOLEAN NOT NULL DEFAULT FALSE
);
